CREATE TABLE IF NOT EXISTS Writer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name NVARCHAR(100) NOT NULL,
    bio TEXT
);

CREATE TABLE IF NOT EXISTS Book (
    id INT AUTO_INCREMENT PRIMARY KEY,
    writer_id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    description TEXT,
    genre NVARCHAR(100),
    total_copies INT NOT NULL DEFAULT 0,
    borrow_copies INT NOT NULL DEFAULT 0,
    FOREIGN KEY (writer_id) REFERENCES Writer(id) ON DELETE NO ACTION ON UPDATE NO ACTION
    
);

CREATE TABLE IF NOT EXISTS Reader (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name NVARCHAR(100) NOT NULL,
    address NVARCHAR(100),
    contact NVARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Book_Order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reader_id INT NOT NULL,
    book_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    FOREIGN KEY (reader_id) REFERENCES Reader(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (book_id) REFERENCES Book(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);